user/config.js

> Check one
> Just add available activity_types

Add available activity_types

---

src/commands/rename.js

> Check one
> Reference any issues here
> Describe your changes
> Check all that apply

Add command -rename for rename the ticket channel

---

src/commands/rename.js
src/index.js

> Check one
every single issue that gets opened
made it good
> Check all that apply

Error if Node is not v12 or higher, fix eslint error etc

---

src/commands/close.js

This allows for staff to easily find ticket ids (at least recent ones).
> Check one
> No
> I have simply added a Ticket ID field to the ticket close message.
> Check all that apply

Add Ticket ID to ticket close message

---

package-lock.json
package.json
src/commands/closeall.js
src/events/message.js

> Check one
Finished #85
Adds arguments to close all tickets older than a specific date. Also modifies the database entry for each message in a ticket channel so `-closeall <timestamp>` closes from the last message, not creation date.
> Check all that apply

Closeall args

---

.gitignore
package.json
src/commands/add.js
src/commands/close.js
src/commands/closeall.js
src/commands/delete.js
src/commands/help.js
src/commands/new.js
src/commands/panel.js
src/commands/remove.js
src/events/debug.js
src/events/error.js
src/events/message.js
src/events/messageDelete.js
src/events/messageReactionAdd.js
src/events/messageUpdate.js
src/events/rateLimit.js
src/events/ready.js
src/events/warn.js
src/index.js

Probably something I spoke about in DMs.
Changed order of event and command export in order to support passing the main logger instance through. Allows for logging everything in files and most likely includes a performance boost. I know V3 is coming soon™️ but this is just for now.

Only create a logger instance once

---

src/events/messageReactionAdd.js

- This includes patches (bug fixes, documentation changes etc)
No.
Fixed topic when using panel to create a ticket
- This is tested and works

fix topic when using panel

---

src/commands/close.js
src/commands/closeall.js

#135 
Fixed catching if user has closed DMs

proper DM catching if user has them closed

---

README.md

update readme and fix typo

---

src/locales/en-GB.json
src/locales/en-US.json
src/locales/hi-IN.json
src/locales/ko-KR.json
src/locales/ru-RU.json
src/locales/th-TH.json

- [X ] This includes minor changes (minimal usage changes, minor new features)
Nope
Just fixed language error in request_topic section where it says `in a a`, it should be `in a`
- [X ] My changes have been tested and confirmed to work

Fix some language errors 

---

src/locales/en-GB.json
src/locales/en-US.json
src/locales/fr-FR.json
src/locales/hi-IN.json
src/locales/hu.json
src/locales/id-ID.json
src/locales/it-IT.json
src/locales/ko-KR.json
src/locales/no-NO.json
src/locales/pl-PL.json
src/locales/ru-RU.json
src/locales/th-TH.json

- Fixed the same typo in various locales. In the stats command, "Discord Tickets" was "Discord TIckets"

style: Typo fix

---

src/locales/es-ES.json

**A translation of the latest version into Spanish v.3.1.3 has been made **

updated language trans

---

src/locales/id-ID.json

update 100% ID language

---

pterodactyl.egg.json

This is not related to any issues currently.
Updates the default version of the bot installed to the latest version, `3.1.3` and updates the installation environment to NodeJS 16 (Bullseye) Slim.

refactor(pterodactyl): Update the Pterodactyl Egg

---

src/locales/it-IT.json

No
Rewrite of /src/locale/it-IT.yml
I did a complete rewrite of it-IT.yml to add missing keys and do a better translation. 

Update and Rewrite of it-IT.yml

---

Dockerfile
compose.Dockerfile
docker-compose.yml

Not related to an issue.
Taking inspiration from #227, I've changed around the Dockerfile + compose configuration a bit.
- Switched to the Alpine image, using a non-root user (with UID 1000)
- Add Docker compose configuration (with changes to the other mentioned PR)
Side note: Currently, pnpm installs all development packages when trying to install an extra package (see line 17 in compose.Dockerfile about mysql2), it's a workaround for now but not complete.

feat(docker): Docker improvements

---

Dockerfile
docker-compose.yml

**Added working docker-compose.yml after Earth's Dockerfile edits**

Add Docker-compose

---

src/routes/auth/logout.js

Fixed users can't logout
Edited logout.js to remove the "token" cookie

[V4] Fixed logout

---

package.json
src/i18n/pt-BR.yml

Translation to Brazilian Portuguese

---

src/i18n/pt-BR.yml

No.
Accents and better "release" word translation

feat(i18n): update Portuguese (Brazil) translations [skip ci]

---

src/commands/slash/tickets.js

- added ticket chanel id for closed tickets to make it easier to find transcripts

added ticket channel id for closed tickets

---

Dockerfile
scripts/start.sh

- [x ] This includes patches (bug fixes)
No
Change start.sh to use /bin/sh as it previously for docker alpine compatibility and check if the script is running within docker to override the BASH_SOURCE simply with /app. Dockerfile has added a simple boolean to denote that docker is in use.
- [x ] My changes use consistent code style
- [ x] My changes have been tested and confirmed to work

Fix docker integration

---

src/i18n/zh-TW.yml

feat(18n): add Traditional Chinese(zh-TW) translations

---

src/i18n/tr.yml

No, is not
Turkish language support is now complete

feat(i18n): make turkish language support more comprehensive

---

.eslintrc.json
package.json
pnpm-lock.yaml
scripts/export.mjs
scripts/import.mjs

Add scripts to export and import individual guilds' data to
1. make it easier for people self-hosting migrate from SQLite to MySQL/PostgreSQL
2. enable migration to or from the public bot

feat(scripts): data export and import scripts

---

src/commands/slash/rename.js
src/i18n/en-GB.yml

https://app.feedbacky.net/i/add-rename-command.3613
https://app.feedbacky.net/i/add-a-rename-command.4173
https://app.feedbacky.net/i/rename-ticket-function.5133
https://app.feedbacky.net/i/rename-command.5493
- implement the /rename command to allow staff to change the name of a topic
- validate that the new name is between 1 and 100 characters
- Validate rate limit (2× per 10 minutes)
- return appropriate success or error messages based on the validation

Added /rename command

---

src/i18n/vi.yml

Update Vietnamese Translation

---

Dockerfile

chore: clean up dockerfile
